// src/naive-ui.ts
import {
  create,
  NConfigProvider,
  NLayout,
  NLayoutHeader,
  NLayoutContent,
  NLayoutSider,
  NButton,
  NInput,
  NDataTable,
  NTag,
  NDatePicker,
  NSelect,
  NSpace,
  NForm,
  NFormItem,
  NPagination,
  NDrawer,
  NDrawerContent,
  NDescriptions,
  NDescriptionsItem,
  NSpin,
  NDivider,
  NEmpty,
  NCard,
  NIcon,
  NText,
  NMenu,
  NModal,
  NScrollbar,
} from "naive-ui";

export function createNaiveUi() {
  return create({
    components: [
      NConfigProvider,
      NLayout,
      NLayoutHeader,
      NLayoutContent,
      NLayoutSider,
      NButton,
      NInput,
      NDataTable,
      NTag,
      NDatePicker,
      NSelect,
      NSpace,
      NForm,
      NFormItem,
      NPagination,
      NDrawer,
      NDrawerContent,
      NDescriptions,
      NDescriptionsItem,
      NSpin,
      NDivider,
      NEmpty,
      NCard,
      NIcon,
      NText,
      NMenu,
      NModal,
      NScrollbar,
    ],
  });
}
